
project_id = "lmovpaablzagtkedhbtb"

[functions.gemini]
verify_jwt = false
timeout_seconds = 60

[functions.openai]
verify_jwt = false
timeout_seconds = 60

[functions.groq]
verify_jwt = false
timeout_seconds = 60

[functions.deepseek]
verify_jwt = false
timeout_seconds = 60
